[package]
name = "Todo-Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
dotenv = "0.15.0"
jsonwebtoken = "9.3.0"
mongodb = "3.1.0"
serde = { version = "1.0.210", features = ["derive"] }
wrap = "0.1.0"
